# Generated by Django 4.2.7 on 2025-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="momo_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="momo_payment_type",
            field=models.CharField(
                choices=[
                    ("ATM", "Thẻ ATM"),
                    ("CC", "Thẻ Credit Card"),
                    ("WALLET", "Ví MoMo"),
                    ("QR", "QR Code"),
                ],
                default="ATM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="momo_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("momo", "MoMo"),
                    ("qr", "QR Code"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cod", "Cash on Delivery"),
                ],
                default="momo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Chờ thanh toán"),
                    ("paid_successfully", "Đã thanh toán thành công"),
                    ("payment_failed", "Thanh toán thất bại"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
