# Generated by Django 4.2.7 on 2025-12-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_momo_order_id_payment_momo_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Chờ thanh toán"),
                    ("paid_successfully", "Đã thanh toán"),
                    ("payment_failed", "Thanh toán thất bại"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
