# Generated by Django 6.0 on 2026-01-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Chờ thanh toán"),
                    ("deposit_paid", "Đã cọc 50%"),
                    ("paid_successfully", "Đã thanh toán"),
                    ("payment_failed", "Thanh toán thất bại"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
