# Generated by Django 4.2.7 on 2025-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên tour")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Mô tả")),
                ("location", models.CharField(max_length=100, verbose_name="Địa điểm")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Thời gian (ngày)"),
                ),
                (
                    "max_people",
                    models.PositiveIntegerField(verbose_name="Số người tối đa"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
                "ordering": ["-created_at"],
            },
        ),
    ]
