# Generated by Django 4.2.7 on 2025-12-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tours/", verbose_name="Ảnh")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt text"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Ảnh chính"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tours.tour",
                        verbose_name="Tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh Tour",
                "verbose_name_plural": "Ảnh Tours",
            },
        ),
    ]
