# Generated by Django 6.0 on 2026-01-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tourimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ],
                        verbose_name="Đánh giá",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Nhận xét")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Hiển thị trên trang chủ",
                        verbose_name="Nổi bật",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tours.tour",
                        verbose_name="Tour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
                "ordering": ["-created_at"],
                "unique_together": {("tour", "user")},
            },
        ),
    ]
