# Generated by Django 6.0 on 2026-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_alter_review_unique_together_review_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="is_hot",
            field=models.BooleanField(default=False, verbose_name="Tour Hot 🔥"),
        ),
    ]
