# Generated by Django 6.0 on 2026-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_tour_is_hot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="is_hot",
            field=models.BooleanField(
                default=False,
                help_text="Đánh dấu tour này là hot/bán chạy",
                verbose_name="Tour Hot 🔥",
            ),
        ),
    ]
