# Generated by Django 4.2.7 on 2026-02-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_alter_tour_is_hot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
    ]
