# Generated by Django 4.2.7 on 2026-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_remove_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Giá"
            ),
        ),
    ]
