# Generated by Django 4.2.7 on 2025-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_conversation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="conversation_state",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Trạng thái hội thoại",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="message_text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="message_type",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot"), ("system", "System")],
                max_length=10,
            ),
        ),
    ]
