# Generated by Django 4.2.7 on 2025-12-31 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram_bot", "0003_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="django_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User liên kết",
            ),
        ),
    ]
