# Generated by hand to add deposit fields
from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_percentage',
            field=models.DecimalField(default=decimal.Decimal('0.00'), max_digits=4, decimal_places=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(default=decimal.Decimal('0.00'), max_digits=10, decimal_places=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
