# Generated by Django 4.2.7 on 2025-12-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_add_deposit_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Đang chờ"),
                    ("paid", "Đã thanh toán"),
                    ("refunded", "Đã hoàn tiền"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Đang chờ"),
                    ("confirmed", "Đã xác nhận"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
