# Generated by Django 6.0 on 2026-01-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_payment_status_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="custom_itinerary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Lịch trình AI Design"
            ),
        ),
    ]
