# Generated by Django 4.2.7 on 2026-02-12 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_custom_itinerary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
