# Generated by Django 4.2.7 on 2025-12-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "cccd",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CCCD/CMND"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=1,
                        null=True,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ người dùng",
                "verbose_name_plural": "Hồ sơ người dùng",
            },
        ),
    ]
